[package]
name = "QiaraAutomationV1"
version = "1.0.0"
authors = []

[addresses]
dev = "0x6341ca6cd563e9317718102d312a2281fbb9b3e4506b4871d98dab4085f94ec1"
supra_framework = "0x1"
[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.AptosStdlib]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/aptos-stdlib"

[dependencies.QiaraTokensV1]
git = 'https://github.com/cnhuya/AEXIS-CODE.git'
rev = 'main'
subdir = 'Supra/TokensCore'

[dev-dependencies]