[package]
name = "QiaraEventV2"
version = "1.0.0"
authors = []

[addresses]
dev = "0x434efed497f5b9ed8f975dd60df271297e35a1bbe9e4a17bc65920273bfca1c6"
supra_framework = "0x1"
std = "0x1"
aptos_std = "0x1"
Extensions = "0x1"
[dev-addresses]


[dependencies.AptosStdlib]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/aptos-stdlib"

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"


[dev-dependencies]