[package]
name = "QiaraEventV34"
version = "1.0.0"
authors = []

[addresses]
dev = "0xb5a924dde82fd1e3dd0d1c99e863ccce2732a0e0e80c338f8eb3a4cd7ae5aed4"
supra_framework = "0x1"
std = "0x1"
aptos_std = "0x1"
Extensions = "0x1"
[dev-addresses]


[dependencies.AptosStdlib]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/aptos-stdlib"

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"


[dev-dependencies]