[package]
name = "QiaraMultiAssetVaultV1"
published-at = "0x01cc22bcd2f0d43783f2d1e53065b284d7a2a1e051741a5747a303e9ef6c6255"
edition = "2024.beta"

[addresses]
std = "0x1"
QiaraMultiAssetVaultV1 = "0x01cc22bcd2f0d43783f2d1e53065b284d7a2a1e051741a5747a303e9ef6c6255"
QiaraVariablesV1 = "0x57c4c6affee05e7431188c1fa6b349f580600f72049b23cf1c867fc7d176046a"
QIARA_ZKV1 = "0x57c4c6affee05e7431188c1fa6b349f580600f72049b23cf1c867fc7d176046a"

[dependencies.QiaraVariablesV1]
git = 'https://github.com/cnhuya/AEXIS-CODE.git'
rev = 'main'
subdir = 'Sui/Variables'
