[package]
name = "QiaraMultiAssetVaultV1"
published-at = "0x1783ea094a4a028779872a7fa2c65a6eaf5e89fe451bcc116033b145fc496cab"
edition = "2024.beta"

[addresses]
std = "0x1"
multi_asset_vault = "0x1783ea094a4a028779872a7fa2c65a6eaf5e89fe451bcc116033b145fc496cab"

[dependencies.QiaraVariablesV1]
git = 'https://github.com/cnhuya/AEXIS-CODE.git'
rev = 'main'
subdir = 'Sui/Variables'
