[package]
name = "QiaraMultiAssetVaultV1"
published-at = "0x5599731e2cc55ab0f559edbf225a8631cea1c5a447a1f58be4502230678b65e6"
edition = "2024.beta"

[addresses]
std = "0x1"
QiaraMultiAssetVaultV1 = "0x5599731e2cc55ab0f559edbf225a8631cea1c5a447a1f58be4502230678b65e6"

[dependencies.QiaraVariablesV1]
git = 'https://github.com/cnhuya/AEXIS-CODE.git'
rev = 'main'
subdir = 'Sui/Variables'
