[package]
name = "QiaraMultiAssetVaultV1"
published-at = "0x7ffa64b275edde01982fe35808658a321ed32e6a11b8c9be866d7e5c54f59f3e"
edition = "2024.beta"

[addresses]
std = "0x1"
QiaraMultiAssetVaultV1 = "0x7ffa64b275edde01982fe35808658a321ed32e6a11b8c9be866d7e5c54f59f3e"

[dependencies.QiaraVariablesV1]
git = 'https://github.com/cnhuya/AEXIS-CODE.git'
rev = 'main'
subdir = 'Sui/Variables'
