[package]
name = "QiaraVariablesV1"
published-at = "0xdb8efd0580db767ea034d6c46092a7f5ca717e8b520363d06fc3302bea05fc4a"
edition = "2024.beta"

[addresses]
std = "0x1"
QiaraVariablesV1 = "0xdb8efd0580db767ea034d6c46092a7f5ca717e8b520363d06fc3302bea05fc4a"
QIARA_ZKV1 = "0xdb8efd0580db767ea034d6c46092a7f5ca717e8b520363d06fc3302bea05fc4a"
QiaraVariablesReadV1 = "0xdb8efd0580db767ea034d6c46092a7f5ca717e8b520363d06fc3302bea05fc4a"