[package]
name = "QiaraVariablesV1"
published-at = "0x7eb0fe967bfd67453b01ebed53ecb866d18da59b4b4dc679b4ea99860a5e63ec"
edition = "2024.beta"

[addresses]
std = "0x1"
QiaraVariablesV1 = "0x7eb0fe967bfd67453b01ebed53ecb866d18da59b4b4dc679b4ea99860a5e63ec"
QIARA_ZKV1 = "0x7eb0fe967bfd67453b01ebed53ecb866d18da59b4b4dc679b4ea99860a5e63ec"
QiaraVariablesReadV1 = "0x7eb0fe967bfd67453b01ebed53ecb866d18da59b4b4dc679b4ea99860a5e63ec"