[package]
name = "QiaraVariablesV1"
published-at = "0xed5b659a8746c2486864980b995d738a978495b17987406cb120b1d20678d01d"
edition = "2024.beta"

[addresses]
std = "0x1"
QiaraVariablesV1 = "0xed5b659a8746c2486864980b995d738a978495b17987406cb120b1d20678d01d"
QIARA_ZKV1 = "0xed5b659a8746c2486864980b995d738a978495b17987406cb120b1d20678d01d"
QiaraVariablesReadV1 = "0xed5b659a8746c2486864980b995d738a978495b17987406cb120b1d20678d01d"