[package]
name = "QiaraDelegatorV1"
published-at = "0xa43215391c8d3d1757a304cdbfca24c429d43fe91119ec9ec57575dbf02bb093"
edition = "2024.beta"

[addresses]
std = "0x1"
QiaraDelegatorV1 = "0xa43215391c8d3d1757a304cdbfca24c429d43fe91119ec9ec57575dbf02bb093"
QiaraExtractorV1 = "0xa43215391c8d3d1757a304cdbfca24c429d43fe91119ec9ec57575dbf02bb093"
QiaraMultiAssetVaultV1 = "0x01cc22bcd2f0d43783f2d1e53065b284d7a2a1e051741a5747a303e9ef6c6255"

[dependencies.QiaraMultiAssetVaultV1]
git = 'https://github.com/cnhuya/AEXIS-CODE.git'
rev = 'main'
subdir = 'Sui/Vaults'
