[package]
name = "QiaraDelegatorV1"
published-at = "0xfa4985eec4732d4b8965244a85f6b6b72433a96d4c95668ed676635eca60676b"
edition = "2024.beta"

[addresses]
std = "0x1"
QiaraDelegatorV1 = "0xfa4985eec4732d4b8965244a85f6b6b72433a96d4c95668ed676635eca60676b"
QiaraExtractorV1 = "0xfa4985eec4732d4b8965244a85f6b6b72433a96d4c95668ed676635eca60676b"


[dependencies.QiaraMultiAssetVaultV1]
git = 'https://github.com/cnhuya/AEXIS-CODE.git'
rev = 'main'
subdir = 'Sui/Vaults'
