    [package]
    name = "QiaraMarketV5"
    version = "2.1.1"
    authors = []

    [addresses]
    dev = "0xc536f11396d0510d90b021cbae973ab1f71155e8ff32c9d544bfb48212b11ac9"
    supra_framework = "0x1"
    std = "0x1"
    aptos_std = "0x1"
    Extensions = "0x1"
    [dev-addresses]

    [dependencies.SupraFramework]
    git = "https://github.com/Entropy-Foundation/aptos-core.git"
    rev = "dev"
    subdir = "aptos-move/framework/supra-framework"

    [dependencies.core]
    git = "https://github.com/Entropy-Foundation/dora-interface.git"
    rev = "master"
    subdir = "supra/testnet/core"

    [dependencies.AptosStdlib]
    git = "https://github.com/Entropy-Foundation/aptos-core.git"
    rev = "dev"
    subdir = "aptos-move/framework/aptos-stdlib"

    [dependencies.QiaraStorageV1]
    git = 'https://github.com/cnhuya/AEXIS-CODE.git'
    rev = 'main'
    subdir = 'Supra/Storage'

    [dependencies.QiaraMarginV8]
    git = 'https://github.com/cnhuya/AEXIS-CODE.git'
    rev = 'main'
    subdir = 'Supra/Margin'

    [dependencies.QiaraMathV1]
    git = 'https://github.com/cnhuya/AEXIS-CODE.git'
    rev = 'main'
    subdir = 'Supra/Math'

    [dependencies.QiaraTokensV6]
    git = 'https://github.com/cnhuya/AEXIS-CODE.git'
    rev = 'main'
    subdir = 'Supra/TokensCore'

    [dependencies.QiaraTypesV5]
    git = 'https://github.com/cnhuya/AEXIS-CODE.git'
    rev = 'main'
    subdir = 'Supra/Types'

    [dependencies.QiaraAutomationV1]
    git = 'https://github.com/cnhuya/AEXIS-CODE.git'
    rev = 'main'
    subdir = 'Supra/AutoCustom'

    [dependencies.QiaraEventV8]
    git = 'https://github.com/cnhuya/AEXIS-CODE.git'
    rev = 'main'
    subdir = 'Supra/Event'

    [dependencies.QiaraSharedV6]
    git = 'https://github.com/cnhuya/AEXIS-CODE.git'
    rev = 'main'
    subdir = 'Supra/Shared'

    [dev-dependencies]