[package]
name = "Qiara_Bluefin_Interface"
edition = "2024.beta"

[addresses]
std = "0x1"


[dependencies.Qiara]
git = "https://github.com/cnhuya/QIARA-CODE.git"
subdir = "Sui/Qiara"
rev = "main"

    