    [package]
    name = "QiaraStakingV10"
    version = "2.1.1"
    authors = []

    [addresses]
    dev = "0xd4fcdba413ff103eec996a07b795847a8b4ce5c328d35d9843dc5ec2230de605"
    supra_framework = "0x1"
    std = "0x1"
    aptos_std = "0x1"
    Extensions = "0x1"
    [dev-addresses]

    [dependencies.SupraFramework]
    git = "https://github.com/Entropy-Foundation/aptos-core.git"
    rev = "dev"
    subdir = "aptos-move/framework/supra-framework"

    [dependencies.core]
    git = "https://github.com/Entropy-Foundation/dora-interface.git"
    rev = "master"
    subdir = "supra/testnet/core"

    [dependencies.AptosStdlib]
    git = "https://github.com/Entropy-Foundation/aptos-core.git"
    rev = "dev"
    subdir = "aptos-move/framework/aptos-stdlib"

    [dependencies.QiaraTypesV27]
    git = 'https://github.com/cnhuya/AEXIS-CODE.git'
    rev = 'main'
    subdir = 'Supra/Types'

    [dependencies.QiaraTokensV45]
    git = 'https://github.com/cnhuya/AEXIS-CODE.git'
    rev = 'main'
    subdir = 'Supra/TokensCore'

    [dependencies.QiaraStakingThirdPartyV3]
    git = 'https://github.com/cnhuya/AEXIS-CODE.git'
    rev = 'main'
    subdir = 'Supra/StakingThirdParty'

    [dev-dependencies]