[package]
name = "Qiara"
published-at = "0x0faedf91493e1610c053c4abd321384236e11d8e3c3ceefb624fe0584eb46382"
edition = "2024.beta"

[addresses]
std = "0x1"
#Qiara = "0x0"
Qiara = "0x0faedf91493e1610c053c4abd321384236e11d8e3c3ceefb624fe0584eb46382"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }