[package]
name = "Qiara"
published-at = "0xb4d224c14d4d26ac8c5202edfa938e3ae39b6bc6c4f67149817e3a44d0476682"
edition = "2024.beta"

[addresses]
std = "0x1"
#Qiara = "0x0"
Qiara = "0xb4d224c14d4d26ac8c5202edfa938e3ae39b6bc6c4f67149817e3a44d0476682"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }