[package]
name = "QiaraHelperV25"
version = "1.0.0"
authors = []

[addresses]
dev = "0xad4689eb401dbd7cff34d47ce1f2c236375ae7481cdaca884a0c2cdb35b339b0"
supra_framework = "0x1"
[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.AptosStdlib]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/aptos-stdlib"

[dependencies.QiaraTypesV11]
git = 'https://github.com/cnhuya/AEXIS-CODE.git'
rev = 'main'
subdir = 'Supra/Types'

[dependencies.QiaraStorageV30]
git = 'https://github.com/cnhuya/AEXIS-CODE.git'
rev = 'main'
subdir = 'Supra/Storage'

[dependencies.QiaraMarketV36]
git = 'https://github.com/cnhuya/AEXIS-CODE.git'
rev = 'main'
subdir = 'Supra/Market'

[dependencies.QiaraVerifiedTokensV42]
git = 'https://github.com/cnhuya/AEXIS-CODE.git'
rev = 'main'
subdir = 'Supra/VerifiedTokens'



[dev-dependencies]